apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: full-cnb
spec:
  tag: ericm24/kpack-builder:latest
  serviceAccountRef:
    name: dockerhub-auth
    namespace: default
  stack:
    name: full-cnb
    kind: ClusterStack
  store:
    name: buildpack-store
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/java
