apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: full-cnb
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: paketobuildpacks/build:full-cnb
  runImage:
    image: paketobuildpacks/run:full-cnb
