apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: app-builder
spec:
  tag: semmet95/kpack:app-builder
  serviceAccountRef:
    name: default
    namespace: default
  stack:
    name: bionic-stack
    kind: ClusterStack
  store:
    name: buildpack-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs