apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: app-image-full-cnb
spec:
  build:
    env:
      - name: BP_JAVA_VERSION
        value: 17.*
        name: BP_LOG_LEVEL
        value: DEBUG
  builder:
    kind: ClusterBuilder
    name: full-cnb
  cache:
    volume:
      size: "1.5Gi"
  serviceAccountName: dockerhub-auth
  source:
    blob:
      url: https://storage.googleapis.com/build-service/sample-apps/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar
  tag: ericm24/kpack-image:full-cnb
