apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: app-image
spec:
  tag: semmet95/kpack-image:teammates
  serviceAccountName: dockerhub-auth
  builder:
    kind: ClusterBuilder
    name: app-builder
  source:
    git:
      url: https://github.com/TEAMMATES/teammates
      revision: master
