apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: app-image
spec:
  tag: https://github.com/spring-io/initializr
  builder:
    kind: ClusterBuilder
    name: app-builder
  source:
    git:
      url: spring-io-initialzr
      revision: main
