apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-creds
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJpbmRleC5kb2NrZXIuaW8iOiB7CgkJCSJhdXRoIjogIlpYSnBZMjB5TkRwa1kydHlYM0JoZEY5UVZHMVBTa3R2TkdaelkzWTRTVk5mUjJ3NE9XdDFkekJSU1djPSIKCQl9Cgl9Cn0=

